export const compliments = [
	'Sick!',
	'Nice!',
	'👏',
	'Excellent.',
	'Oh Dang!',
	'Smart.',
	'Fantastic.',
	'Love to see it.',
	'Okay!',
	'Great.',
	'Beautifull',
	'Knew you could do it.',
	'🧙',
	'🧙‍♀️',
	// this is a joke, pls remove later
	'Nice, Tim?',
	'Nice, Madeline?',
	'Nice, Anna?',
	'Nice, Kathryn?',
	'Nice, Alex?',
	'Nice, David?',
	'Nice, Emily?',
	'Nice, Ethan?',
	'Nice, Grace?',
	'Nice, Henry?',
	'Nice, Isabella?',
	'Nice, Jackson?',
	'Nice, Lily?',
	'Nice, Fred?'
];
